# -*- coding: utf-8 -*-
"""Notifications. A normal user may only notify themselves; genuine
cross-user notifications are generated by the endpoint that causes them."""

from flask import Blueprint, jsonify

from athletix.schemas import requests as rq
from athletix.security.ratelimit import too_many
from athletix.security.session import current_user, login_required
from athletix.services import messaging as messaging_service
from athletix.validation import body

bp = Blueprint('notifications', __name__)


@bp.post("/notifications")
@login_required
def push_notification():
    """Create a notification.

    Previously this took `toId` straight from the request body with no check
    at all, so any logged-in user could push arbitrary text into any other
    user's feed - an open phishing channel. Now:

      * a normal user may only notify themselves (reminders);
      * admins and owners may notify anyone (operator announcements);
      * every genuinely cross-user notification the product needs (new
        message, new rating) is generated server-side by the endpoint that
        causes it, never by the client.
    """
    u = current_user()
    limited = too_many("notify", str(u["id"]))
    if limited:
        return limited
    d = rq.NotificationRequest.load(body())
    messaging_service.push_notification(u, d["toId"], d["text"])
    return jsonify(ok=True)


@bp.post("/notifications/read")
@login_required
def read_notifications():
    """Mark notifications read. Scoped to the caller by the WHERE clause -
    there is no id in the request to point somewhere else."""
    messaging_service.mark_notifications_read(current_user())
    return jsonify(ok=True)
